kind: Service
apiVersion: v1
metadata:
  name: app-service-pay
spec:
  type: LoadBalancer
  selector:
    app: service-pay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
      name: http
